name = "Anamari Slemensek"
rol = "Student Assistant and English Major"
email = "anamari.slemensek@uni-graz.at"
phone = "+43 660 4474 163"
birthday = "July 16, 1999"
location = "Graz, Styria, Austria"
avatar = "./config/assets/avatars/my-avatar.png"
username = "aamsii" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd" 
presentation = """
I'm a Student Assistant from Graz, Austria, working in web design and social media. I enjoy turning complex problems into simple, beautiful and intuitive designs.

My job is to support the Center of Inter-American Studies with its web related tasks as well as social media management.
"""
