[[post]]
category = "Index"
title = "Masculinities Ageing Between Cultures - Relationality, Kinship and Care in Dialogue"
subtitle = "Editor"
datetime = "2024-03-17"
image = "./config/assets/posts/blog-1.jpg"
url = "https://www.transcript-verlag.de/978-3-8376-6906-0/masculinities-ageing-between-cultures/?number=978-3-8394-6906-4"

[[post]]
category = "Frontend and Backend web development"
title = "Webpage Center for Inter-American Studies"
subtitle = "Use of HTML in CMS and simpler programs such as TYPO3"
datetime = "2023-02-01"
image = "./config/assets/posts/blog-2.jpg"
url = "https://interamerikanistik.uni-graz.at/de/neuigkeiten/"

[[post]]
category = "Erasmus Students Network"
title = "Buddy Incoming Volunteer"
subtitle = "As a 'Buddy,' I welcome incoming students to Graz. I show them around and help them with issues around their studies and everyday life in Graz."
datetime = "2022-02-01"
image = "./config/assets/posts/blog-3.jpg"
url = "https://orientation.uni-graz.at/de/planning-the-arrival/erasmus-student-network-buddy-programme/"

[[post]]
category = "English and German Tutoring"
title = "Tutoring of Children and Adults"
subtitle = "Education is something I value greatly, and I love to give back to the community. I started tutoring children at the primary school level as well as adults seeking employment to make use of the knowledge I have gained throughout my studies, including 'Legal English', 'Commercial English' and 'Business English.'"
datetime = "2018-01-01"
image = "./config/assets/posts/blog-4.jpg"
